"""
Django settings for AuroNow project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5(azb_wl5dcp4khcbrjywyz-6!a)4i6b6qi5z)eto$+p2x%7w$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # custom apps
    'shops',
    'auroUser',
    # Third party apps (django-tailwind 3.8)
    'tailwind',
    'theme',
    'django_browser_reload',
]


# Tailwind settings
TAILWIND_APP_NAME = 'theme'  # This is the name of the app that will be used to generate the tailwind files
INTERNAL_IPS = [
    "127.0.0.1",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

ROOT_URLCONF = 'AuroNow.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AuroNow.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'auronow',          # Database name
        'USER': 'root',            # MySQL username
        'PASSWORD': 'admin',        # MySQL password
        'HOST': 'localhost',        # Change this to 'localhost' instead of '127.0.0.2'
        'PORT': '3306',             # Default MySQL port
    }
}


# Manually load the .env file
from dotenv import load_dotenv
load_dotenv()

# Initialize the environment variable reading system
env = environ.Env()
# reading .env file if exists
environ.Env.read_env()


# # Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587  # For TLS
EMAIL_USE_TLS = True  # Use TLS for secure connection
EMAIL_HOST_USER = env('EMAIL_HOST_USER')  # Your Gmail address
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')  # The app password you generated
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # Optional: Default sender email for outgoing mails


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
AUTH_USER_MODEL = 'shops.ShopOwner'
# URL to use when referring to static files located in STATICFILES_DIRS
STATIC_URL = '/static/'
# If you want to specify additional directories to look for static files
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]


# URL for accessing uploaded files
MEDIA_URL = '/media/'
# Directory where uploaded files will be stored
MEDIA_ROOT = [os.path.join(BASE_DIR, 'media')]

# For collecting static files in production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# it is for the djando-tailwind package
NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"

# settings.py
# LOGIN_REDIRECT_URL = 'dashboard_home'
# LOGOUT_REDIRECT_URL = 'dashboard_login'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
