# Generated by Django 5.1.7 on 2025-04-25 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auroUser', '0002_bookappointment_created_at_bookappointment_end_time_and_more'),
        ('shops', '0011_staff_is_active_staff_staff_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='shops.staff'),
        ),
    ]
