# Generated by Django 5.1.7 on 2025-05-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auroUser', '0003_bookappointment_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Karachi', max_length=255),
        ),
    ]
