# Generated by Django 5.1.7 on 2025-05-18 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auroUser', '0005_alter_user_password_userpasswordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpasswordresettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
