# Generated by Django 5.1.7 on 2025-04-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopimage',
            name='image_url',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together={('phone', 'shop')},
        ),
    ]
