# Generated by Django 5.1.7 on 2025-04-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_shopimage_image_url_alter_staff_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopimage',
            name='image_url',
            field=models.ImageField(upload_to='shop_images/'),
        ),
    ]
