# Generated by Django 5.1.7 on 2025-04-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_shopimage_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopimage',
            old_name='image_url',
            new_name='image',
        ),
    ]
