# Generated by Django 5.1.7 on 2025-04-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_service_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopimage',
            old_name='shop_email',
            new_name='shop',
        ),
        migrations.RemoveField(
            model_name='shopimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='shopimage',
            name='shop_image',
            field=models.ImageField(default='', upload_to='shop_images/'),
        ),
    ]
