# Generated by Django 5.1.7 on 2025-04-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_rename_shop_email_shopimage_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopowner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shopowner',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopowner',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
