# Generated by Django 5.1.7 on 2025-04-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_shopowner_groups_shopowner_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopimage',
            name='shop_image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images/'),
        ),
    ]
