# Generated by Django 5.1.7 on 2025-04-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_shoptiming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoptiming',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shoptiming',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
