# Generated by Django 5.1.7 on 2025-04-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_alter_shoptiming_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_picture',
            field=models.ImageField(blank=True, null=True, upload_to='staff_pictures/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='work_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='work_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
