# Generated by Django 5.1.7 on 2025-05-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_staff_is_active_staff_staff_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopowner',
            name='shop_status_bool',
            field=models.BooleanField(default=True),
        ),
    ]
