# Generated by Django 5.1.7 on 2025-05-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0012_shopowner_shop_status_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
    ]
