# Generated by Django 5.1.7 on 2025-05-03 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0013_service_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_image',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='shop',
        ),
    ]
