# Generated by Django 5.1.7 on 2025-05-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0014_remove_service_service_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
    ]
