# Generated by Django 5.1.7 on 2025-05-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0015_service_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopowner',
            name='city',
            field=models.CharField(default='Karachi', max_length=255),
        ),
    ]
