# Generated by Django 5.1.7 on 2025-05-18 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0016_shopowner_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='shops.shopowner'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='shops.shopowner'),
        ),
        migrations.AlterField(
            model_name='service',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='shops.shopowner'),
        ),
        migrations.AlterField(
            model_name='shopimage',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shops.shopowner'),
        ),
        migrations.AlterField(
            model_name='shoptiming',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timings', to='shops.shopowner'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='shops.shopowner'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='shops.shopowner'),
        ),
    ]
